version: 2.1
orbs:
  test-orb: smitkumar-patel/test-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/
  branches:
    only:
      - main

workflows:
  test-deploy:
    jobs:
      # Added this to run the node app
      - test-orb/post-to-ms-teams:
          ids: "10,20,30,40"
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: smitkumar-patel/test-orb
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - test-orb/post-to-ms-teams
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
